name : try to pages

on:
  push :
    branches: [ "main" ]
  pull_request:
    branches : [ "main" ]

  workflow_dispatch:
# for manually  triggres

# all the permissions for github pages
permissions:
  contents : read
  pages: write
  id-token: write



jobs:
  build:
    runs-on : ubuntu-latest
    steps:
    - name : check
      uses: actions/checkout@v4
      with: 
        fetch_depth: 0  #fetch all history to be better

    - name : setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm" # we could say it will be faster 
        cache-dependency-path: './Frontend/package-lock.json'

    - name : setup the pages
      uses: actions/configure-pages@v1


    - name : install depend.
      working-directory: ./Frontend
      run: |
        npm ci   
        echo "Dependencies was successfully installed "

    - name : build the astro
      working-directory: ./Frontend
      run: |
        npm run build 
        echo "done"

    - name: build the artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: ./Frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: deploy to pages
      id: deployment
      uses: actions/deploy-pages@v4


  






